version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp: